name: Bug Report
description: File a bug report
title: "[Bug]: <title>"
labels: ["Type: Bug"]
body:
- type: checkboxes
  attributes:
    label: Consent
    options:
    - label: I have searched the existing issues and verified that there is no open issue for the same subject.
      required: true
    - label: I understand that the YTMDesktop Elgato Plugin has NO affiliation with Google, YouTube or the YTMDesktop application.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: input
  attributes:
    label: OS
    description: "Which OS are you using?"
    value: Windows
  validations:
    required: true
- type: input
  attributes:
    label: OS Version
    description: "Which OS version are you on?"
    value: "10"
  validations:
    required: true
- type: input
  attributes:
    label: Plugin Version
    description: "Which Version does your plugin has?"
    placeholder: v1.0.4.1
  validations:
    required: true
- type: input
  attributes:
    label: YTMDesktop Version
    description: "Which Version does your YTMDesktop application has?"
    placeholder: v1.13.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: How did you download the software?
    options:
      - Elgato Store
      - GitHub
      - Discord
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
